### ISSUE TITLE
关于休眠唤醒问题

### ISSUE THREAD

**Issue by EvanLin1003** [Anoce0/MSI-B460M-MORTAR-10700-iGPU-OC#1]
大佬 这个休眠唤醒正常不

**Comment by Anoce0** [comment]
好像是休眠有问题，BIOS 打开从外设唤醒的情况下会导致无法进入休眠，我直接从 BIOS 里把外设唤醒关掉了，每次唤醒需要按一下开关。

**Comment by EvanLin1003** [comment]
请教一下 核显hd630 用哪一个config啊

**Comment by Anoce0** [comment]
本来应该用 iGPU 那个 config, 但是我很久没更新它了，建议你手动改下 config.plist
里的  AAPL,ig-platform-id 
改成 
` <data>BwCbPg==</data> `
试下看看。

**Comment by EvanLin1003** [comment]
还是用你这个可以。现在电源唤醒很不错。折腾了三天了。终于好了
